baseURL = "https://bas1ctf.github.io/"
defaultContentLanguage = "en"
languageCode = "en"

title = "Bas1cTF"
theme = "gokarna"
enableRobotsTXT = true

[menu]

  [[menu.main]]
    identifier = "Home"
    pre = "<span data-feather='home'></span>"
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    identifier = "posts"
    url = "/posts/"
    pre = "<span data-feather='book'></span>"
    name = "Posts"
    weight = 2

  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    pre = "<span data-feather='tag'></span>"
    url = "/tags/"
    weight = 3
    
  [[menu.main]]
    identifier = "github"
    url = "https://github.com/Bas1cTF"
    weight = 4
    pre = "<span data-feather='github'></span>"

[params]
  avatarURL = "/images/ghost.png"
  avatarSize = "size-m"
  description = "| Student | CTF Player |"
  accentColor = "#D9389C"
  socialIcons = [
      {name = "twitter", url = "https://twitter.com/Bas1cTF"},
      {name = "hackthebox", url = "https://app.hackthebox.com/profile/467628"},
      {name = "ctftime", url = "https://ctftime.org/user/137143"},
    ]
  metaKeywords = ["Bas1cTF", "HTB", "writeup"]
  #showPostsOnHomePage = "recent"
  footer = "SSBsb3ZlIHlvdTwz"
[markup]
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 4
    ordered = false