baseURL = "http://example.org/"
defaultContentLanguage = "es"
languageCode = "en"

title = "Bas1cTF"

theme = "gokarna"

# Automatically generate robots.txt
enableRobotsTXT = true

[menu]

  [[menu.main]]
    identifier = "Home"
    pre = "<span data-feather='home'></span>"
    url = "/"
    weight = 1

  [[menu.main]]
    # Unique identifier for a menu item
    identifier = "posts"

    url = "/posts/"
    
    # You can add extra information before the name (HTML format is supported), such as icons
    pre = ""

    # You can add extra information after the name (HTML format is supported), such as icons
    post = ""

    # Display name
    name = "Posts"

    # Weights are used to determine the ordering
    weight = 1

  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 2
    
  [[menu.main]]
    identifier = "github"
    url = "https://github.com/Bas1cTF"
    weight = 3
    
    # We use feather-icons: https://feathericons.com/
    pre = "<span data-feather='github'></span>"
[params]
  # URL for the avatar on homepage
  avatarURL = "/avatar.jpg"

  # Choose one of size-xs, size-s, size-m, size-l & size-xl. (Default: size-m)
  avatarSize = ""

  # Description to display on homepage
  description = "wannabe CTF Player | Personal Blog"

  # Accent color is displayed when you hover over <a> tags
  accentColor = "#FF4D4D"

 socialIcons = [
      {name = "twitter", url = "https://twitter.com/Bas1cTF"},
      {name = "hackthebox", url = "https://app.hackthebox.com/profile/467628"},
      {name = "ctftime", url = "https://ctftime.org/user/137143"},
    ]

  # Keywords relevant for SEO
  metaKeywords = ["Bas1cTF", "HTB", "writeup"]

  # If you want to display posts on the homepage, the options are
  # "popular" (order posts by weight), "recent" (order posts by date)
  # or "" (do not display, default option)
  # showPostsOnHomePage = "recent"

  # Footer text
  footer = ""